services:
    ollama-service:
        image: smsrch-prod/ollama
        build:
            dockerfile: ./OllamaDockerfile
            context: ./ollama
        container_name: semantic-search-ollama-service
         # Give access to the host devices (for AMD GPU/Vulkan support)
        devices:
        - "/dev/kfd:/dev/kfd"
        - "/dev/dri:/dev/dri"
        environment:
          - LLM_MODEL_VERSION=embeddinggemma
          - OLLAMA_VULKAN=1
          - MODEL_INSTALLED=0
        volumes:
          - ./model_files:/model_files  # Mount the directory with the trained mode
          - ./ollama_data:/root/.ollama
        # ports:
        #     - "11434:11434"
        healthcheck:
            # test: ["CMD", "ollama", "list"]
            test: [ "CMD-SHELL", "ollama list | grep -q \"embeddinggemma\"" ]
            interval: 1m30s
            timeout: 30s
            retries: 5
            start_period: 30s

    redis-service:
        image: redis:alpine
        container_name: queue-service-redis
        # ports:
        #     - "6379:6379"
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 3s
            retries: 5

    # https://jarrettmeyer.com/software/fastapi-celery/
    tasks-queue:
        build:
            dockerfile: ./AppDockerfile
            target: production
        restart: unless-stopped
        depends_on:
            redis-service:
                condition: service_healthy
        volumes:
            - .:/app
            - ./data:/app/data
        environment:
            - CELERY_RESULT_EXPIRES=900
        command: celery -A app.tasks worker --concurrency=2 --loglevel=INFO
        healthcheck:
            test: ["CMD", "celery", "report"]
            interval: 1m30s
            timeout: 30s
            retries: 5
            start_period: 30s

    chroma-db:
        # https://cookbook.chromadb.dev/running/health-checks/
        image: chromadb/chroma
        container_name: semantic-search-chroma-db
        volumes:
            - ./data/chroma:/data
        # ports:
        #     - "8000:8000"
        command: "run --host 0.0.0.0 --port 8000 --path /data"
        healthcheck:
            test: [ "CMD", "/bin/bash", "-c", "cat < /dev/null > /dev/tcp/localhost/8000" ]
            interval: 30s
            timeout: 10s
            retries: 3

    app:
        build:
            dockerfile: ./AppDockerfile
            target: production
        container_name: semantic-search-app
        environment:
            - REDIS_URL=redis://redis-service:6379
            - CHROMA_DB_HOST=chroma-db
            - CHROMA_DB_PORT=8000
            - CHROMA_DB_COLLECTION_NAME=docs
            - OLLAMA_URL=http://ollama-service:11434
            - LLM_MODEL=embeddinggemma
            - DATA_DIRECTORY=data
        volumes:
            - .:/app
            - ./data:/app/data
        ports:
            - "8080:8080"
        depends_on:
            ollama-service:
                condition: service_healthy
            tasks-queue:
                condition: service_healthy
            chroma-db:
                condition: service_healthy
        command: uvicorn app.main:app --host 0.0.0.0 --port 8080

