services:
    # Mock or Small-scale Ollama for testing
    ollama-test:
        image: smsrch-test/ollama
        container_name: ollama-test
        build:
            dockerfile: ./OllamaDockerfile
            context: ./ollama
        environment:
            - LLM_MODEL_VERSION=locusai/all-minilm-l6-v2
            - OLLAMA_NUM_PARALLEL=4
        healthcheck:
            test: [ "CMD-SHELL", "ollama list | grep -q \"locusai/all-minilm-l6-v2\"" ]
            interval: 10s
            timeout: 5s
            retries: 5

    redis-test:
        image: redis:alpine
        container_name: redis-test
        command: redis-server --save "" --appendonly no
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            interval: 5s
            timeout: 3s
            retries: 5

    chroma-test:
        image: chromadb/chroma
        container_name: chroma-test
        environment:
            - ANONYMIZED_TELEMETRY=False
        healthcheck:
            test: [ "CMD", "/bin/bash", "-c", "cat < /dev/null > /dev/tcp/localhost/8000" ]
            interval: 10s
            timeout: 5s
            retries: 3
        command: run --host 0.0.0.0 --port 8000 --path /tmp

    # The Test Runner Service
    pytest-runner:
        build:
            dockerfile: ./AppDockerfile
            target: development
        container_name: pytest-runner
        environment:
            - REDIS_URL=redis://redis-test:6379
            - CHROMA_DB_HOST=chroma-test
            - CHROMA_DB_PORT=8000
            - CHROMA_DB_COLLECTION_NAME=docs_test
            - OLLAMA_URL=http://ollama-test:11434
            - LLM_MODEL=locusai/all-minilm-l6-v2
            - CELERY_TASK_ALWAYS_EAGER=True # Force sync execution
            - DATA_DIRECTORY=/tmp
        volumes:
            - .:/app
        depends_on:
            redis-test:
                condition: service_healthy
            chroma-test:
                condition: service_healthy
            ollama-test:
                condition: service_healthy
        tmpfs:
            - /tmp:size=50m,mode=1700
        # command: pytest -vv -s tests # Use this if debugging of tests execution is needed
        command: pytest tests
