services:
    ollama:
        image: ollama/ollama
        container_name: ollama
        environment:
          - LLM_MODEL_VERSION=embeddinggemma
        volumes:
          - ./model_files:/model_files  # Mount the directory with the trained mode
          - ./ollama_data:/root/.ollama
          # - ./ollama_entrypoint.sh:/ollama_entrypoint.sh
        ports:
            - "11434:11434"
        logging:
            driver: "none"

    redis:
        image: redis:alpine
        container_name: queue-service-redis
        ports:
            - "6379:6379"
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 3s
            retries: 5

    # https://jarrettmeyer.com/software/fastapi-celery/
    tasks-queue:
        build:
            dockerfile: ./AppDockerfile
        restart: unless-stopped
        depends_on:
            redis:
                condition: service_healthy
        volumes:
            - .:/app
        environment:
            - CELERY_RESULT_EXPIRES=900
        command: celery -A app.tasks worker --concurrency=2 --loglevel=INFO

    app:
        build:
            dockerfile: ./AppDockerfile
        container_name: semantic-search-app
        command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        depends_on:
            - ollama
            - tasks-queue

    # frontend:
    #     build:
    #         - dockerfile: ./FrontendDockerfile
    #     container_name: semantic-search-frontend
    #     ports:
    #         - "5173:5173"
    #     volumes:
    #         - ./frontend:/frontend
    #     depends_on:
    #         - app
